fix path syscall-args search
hugsy/gef-extras pull request #107
Opened 2024-04-19 03:46 UTC by therealdreg

## Description/Motivation/Screenshots

fix syscall-args path search

## How Has This Been Tested ?

"Tested" indicates that the PR works *and* the unit test (i.e. `make test`) run passes without issue.

*  [x] x86-32
*  [x] x86-64
*  [ ] ARM
*  [ ] AARCH64
*  [ ] MIPS
*  [ ] POWERPC
*  [ ] SPARC
*  [ ] RISC-V

## Checklist

*  [x] My code follows the code style of this project.
*  [x] My change includes a change to the documentation, if required.
*  [x] If my change adds new code,
   [adequate tests](https://hugsy.github.io/gef/testing) have been added.
*  [x] I have read and agree to the
   [CONTRIBUTING](https://github.com/hugsy/gef/blob/main/.github/CONTRIBUTING.md) document.

2024-04-20 16:11 UTC, hugsy requested changes

2024-04-20 16:11 UTC, hugsy commented on scripts/syscall_args/__init__.py
> +        caller_frame = inspect.stack()[0]
you might want to using prefer `pathlib.Path(__file__)`

2024-04-20 16:11 UTC, hugsy commented on scripts/syscall_args/__init__.py
> +        path = os.path.join(os.path.dirname(os.path.abspath(path)), "syscall-tables")
same, prefer `pathlib` over legacy `os.path`

2024-04-22 01:00 UTC, hugsy commented
From @therealdreg 

Repro:
```text
root@fr33project:~# bash -c "$(curl -fsSL https://gef.blah.cat/sh)"
root@fr33project:~# wget -q -O- https://github.com/hugsy/gef/raw/main/scripts/gef-extras.sh | sh
```

![image](https://github.com/hugsy/gef-extras/assets/590234/43d52818-de0d-46a0-bc19-ed321dd08f48)


Re-posting here for tracking:
> I could reproduce your issue. there is a problem, but your PR doesn't solve it, it 's just a side effect of it. the problem is that the setting is overwritten by its default value when it shouldn't be
> basically all values are overwritten by their default
tbh that may be tricky to solve quickly, so what I'd suggest you is simply make a gef restore to force reloading the .gef.rc

This PR fixes the visible side-effect rather than the root cause of the issue. One possible way to address this would be to force `gef restore` once the setting `gef.extra_plugins_dir` is changed to a different value. This will fix the issue this PR tries to fix, because the setting is originally correctly set by the `gef-extras.sh` install script.

2024-04-22 01:05 UTC, therealdreg commented
thx for your research @hugsy

2024-04-22 01:05 UTC, closed without merging