Fix Capstone plugin
hugsy/gef-extras pull request #110
Opened 2024-04-23 03:21 UTC by hugsy

## Description/Motivation/Screenshots

## How Has This Been Tested ?

"Tested" indicates that the PR works *and* the unit test (i.e. `make test`) run passes without issue.

*  [ ] x86-32
*  [ ] x86-64
*  [ ] ARM
*  [ ] AARCH64
*  [ ] MIPS
*  [ ] POWERPC
*  [ ] SPARC
*  [ ] RISC-V

## Checklist

*  [ ] My code follows the code style of this project.
*  [ ] My change includes a change to the documentation, if required.
*  [ ] If my change adds new code,
   [adequate tests](https://hugsy.github.io/gef/testing) have been added.
*  [ ] I have read and agree to the
   [CONTRIBUTING](https://github.com/hugsy/gef/blob/main/.github/CONTRIBUTING.md) document.

2024-04-27 09:41 UTC, therealdreg requested changes
The documentation refers to the alias "**cs**," but the alias being registered in the code is: "**cs-dis**"

![image](https://github.com/hugsy/gef-extras/assets/9882181/b6be9a7b-3517-4ada-9bfb-b3e20510753e)

![image](https://github.com/hugsy/gef-extras/assets/9882181/dd3ea95e-a426-4099-8087-fa88628f02b3)

2024-04-27 10:11 UTC, therealdreg commented on scripts/capstone.py
> +        location = int(gdb.parse_and_eval(args.location).address)
```suggestion
        location = location = int(parse_address(args.location))
```

**int(gdb.parse_and_eval(args.location).address)** is not working

2024-04-27 10:42 UTC, therealdreg requested changes
The value from the configuration file is not taken into account.

So, capstone-disassemble.use-capstone is always False (on every boot)

here my conf file:
```
[capstone-disassemble]
use-capstone = True
```

```
gef➤  gef config capstone-disassemble.use-capstone 
──────────────────────────────────────── GEF configuration setting: capstone-disassemble.use-capstone ────────────────────────────────────────
capstone-disassemble.use-capstone (bool) = False

Description:
	Replace the GDB disassembler in the `context` with Capstone
gef➤  
```  

@hugsy **Is it possible that this issue is happening with more plugins?**

2024-04-27 15:45 UTC, hugsy commented
> The value from the configuration file is not taken into account.
> 
> So, capstone-disassemble.use-capstone is always False (on every boot)
> 
> here my conf file:
> 
> ```
> [capstone-disassemble]
> use-capstone = True
> ```
> 
> ```
> gef➤  gef config capstone-disassemble.use-capstone 
> ──────────────────────────────────────── GEF configuration setting: capstone-disassemble.use-capstone ────────────────────────────────────────
> capstone-disassemble.use-capstone (bool) = False
> 
> Description:
> 	Replace the GDB disassembler in the `context` with Capstone
> gef➤  
> ```
> 
> @hugsy **Is it possible that this issue is happening with more plugins?**

This is what I explained to you and partially fixed in #1090

![image](https://github.com/hugsy/gef-extras/assets/590234/d885e98d-0967-4d3c-803e-4d9133baf568)

All gef-extras settings are impacted

2024-04-27 15:54 UTC, therealdreg commented
> > The value from the configuration file is not taken into account.
> > So, capstone-disassemble.use-capstone is always False (on every boot)
> > here my conf file:
> > ```
> > [capstone-disassemble]
> > use-capstone = True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > gef➤  gef config capstone-disassemble.use-capstone 
> > ──────────────────────────────────────── GEF configuration setting: capstone-disassemble.use-capstone ────────────────────────────────────────
> > capstone-disassemble.use-capstone (bool) = False
> > 
> > Description:
> > 	Replace the GDB disassembler in the `context` with Capstone
> > gef➤  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hugsy **Is it possible that this issue is happening with more plugins?**
> 
> This is what I explained to you and partially fixed in #1090
> 
> ![image](https://private-user-images.githubusercontent.com/590234/326189056-d885e98d-0967-4d3c-803e-4d9133baf568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzMxMTcsIm5iZiI6MTcxNDIzMjgxNywicGF0aCI6Ii81OTAyMzQvMzI2MTg5MDU2LWQ4ODVlOThkLTA5NjctNGQzYy04MDNlLTRkOTEzM2JhZjU2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QxNTQ2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDZhODU0YWIyOGIwNTgwODIxOGE0MmVmNzE4NGVkMjM2ZTBlNzY2ODI2M2IzYThmZWY1ZGFlMDdkNWU0Mzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NlAtkHI5HHGYge-iXhbpydZHAmhKyTXh5-8osrL_m-s)
> 
> All gef-extras settings are impacted

And what can we do to fix this? I wouldn’t like to release the next version with this issue...

2024-04-27 15:56 UTC, hugsy commented
> And what can we do to fix this?

`gef restore`

But I think this should not happen with the latest change to gef because now loading gef-extras with `on_changed` callback should result in a config reloading.

2024-04-27 15:57 UTC, therealdreg commented
> > And what can we do to fix this?
> 
> `gef restore`
> 
> But I think this should not happen with the latest change to gef because now loading gef-extras with `on_changed` callback should result in a config reloading.

I am using the last version (GEF+EXTRAS) and the problem is still here :\

2024-06-04 22:45 UTC, therealdreg commented
The command works fine, and the alias is fixed!

[image](https://github.com/hugsy/gef-extras/assets/9882181/71a542ba-7245-4264-abf2-bea585e28d6a)

But on each run capstone is set to false!

![image](https://github.com/hugsy/gef-extras/assets/9882181/a7c0a56f-e46b-4718-94c4-beedab7b1f6f)

![image](https://github.com/hugsy/gef-extras/assets/9882181/84dcd77a-bcc7-47d0-ba29-7b038387bd1c)

2024-06-04 22:48 UTC, therealdreg requested changes
on each run capstone is set to false!

----

dreg@rootkit:~/.config/gef-extras$ git log
commit 0b7041fec0a7a5fcf6913676585f7473a058879d (HEAD -> fix_capstone_disass_switch, origin/fix_capstone_disass_switch)
Author: hugsy <crazy.hugsy@outlook.com>
Date:   Mon Jun 3 09:51:40 2024 -0700

    make dreg happy

commit 296049f7d199a4375267cc3d0db62fb30a420cef (tag: 2024.06, origin/main, origin/HEAD, main)
Author: MinatoTW <shaks19jais@gmail.com>
Date:   Thu May 16 08:39:56 2024 +0530

    64bit libc table generator had $r10 as 4th argument (#113)
    
    ## Description/Motivation/Screenshots
    
    Fixes `scripts/libc_function_args/tables/generator.py` which was wrong using `$r10` as 4th argument

----

GEF: (Standalone)
Blob Hash(/home/dreg/.gef-2024.06.py): 88981e223320723f9df39bd8714ea2d56da4dbee
SHA256(/home/dreg/.gef-2024.06.py): 764738509912bea65f67927691d5fa0421444d1969678208095733fdbf0dd83d
GDB: 15.0.50.20240403-git
GDB-Python: 3.12

2024-06-05 02:39 UTC, hugsy commented
This is a different problem to what this PR fixes (and again it can be fixed by doing `gef restore` in your gdbinit)

2024-06-05 07:04 UTC, therealdreg approved these changes

2024-06-05 07:05 UTC, therealdreg commented
> This is a different problem to what this PR fixes (and again it can be worked around by doing `gef restore` in your gdbinit) In GEF you can do a PR that will execute `gef restore` if `load_plugins_from_directory()` return > 0
> 
> Different problems.

Okay, we'll fix it in another PR. Thanks for your patience :D

2024-06-05 07:15 UTC, therealdreg commented
https://github.com/hugsy/gef/pull/1118 fixes the problem!  thx!

![image](https://github.com/hugsy/gef-extras/assets/9882181/28092cb3-285d-4d40-8f60-0fe41828b547)

2024-06-05 14:54 UTC, merged