Add ARMOpenOCD arch
hugsy/gef-extras pull request #83
Opened 2022-11-08 01:25 UTC by Grazfather

## Description/Motivation/Screenshots

This is for debugging ARM targets through JTAG/SWD using the gdbserver implemented in OpenOCD

## How Has This Been Tested ?

"Tested" indicates that the PR works *and* the unit test (i.e. `make test`) run passes without issue.

 * [ ] x86-32
 * [ ] x86-64
 * [ ] ARM
 * [ ] AARCH64
 * [ ] MIPS        
 * [ ] POWERPC     
 * [ ] SPARC       
 * [ ] RISC-V 
  
## Checklist

- [ ] My PR was done against the `dev` branch, not `main`.
- [ ] My code follows the code style of this project.
- [ ] My change includes a change to the documentation, if required.
- [ ] If my change adds new code, [adequate tests](https://hugsy.github.io/gef/testing) have been added.
- [ ] I have read and agree to the [CONTRIBUTING](https://github.com/hugsy/gef/blob/main/.github/CONTRIBUTING.md) document.

2022-11-08 03:17 UTC, hugsy requested changes

2023-08-25 19:48 UTC, hugsy approved these changes
LGTM

2023-08-26 13:39 UTC, Grazfather commented
Still needs work, mostly in the gef project, but want to have a way for an arch to hint to the memory manager how to map.

2024-01-30 01:33 UTC, hugsy commented
Does this PR still make sense (after #99 got merged)?

2024-01-31 00:59 UTC, Grazfather commented
> Does this PR still make sense (after #99 got merged)?

Yes. That was for BlackMagicProbe, this is for OpenOCD. Updated the description so it makes sense.

Still need to do more testing and write docs.

2024-02-16 18:23 UTC, hugsy requested changes
very cool stuff, too bad I can't test it I'd love to try but the code is sound (very minor stuff to fix)

2024-02-16 18:23 UTC, hugsy commented on archs/arm-blackmagicprobe.py
> +    _example_ = [f"{_cmdline_} --scan /dev/ttyUSB1"
missing comma on the first 3 examples

2024-02-16 18:23 UTC, hugsy commented on docs/commands/gef-openocd-remote.md
shouldn't `gef-bmp-remote` also get some docs?

2024-02-16 22:56 UTC, Grazfather commented on docs/commands/gef-openocd-remote.md
Already has them

2024-02-16 23:00 UTC, Grazfather commented on archs/arm-openocd.py
> +    def __init__(self, host, port, file: str="") -> None:
It's harder to test for a valid path. We want the `file` properly to return something falsy is the path isn't setup and `Path("")` evaluates to True.

2024-10-16 20:19 UTC, PowerUser64 commented
I tested this on a Tiva C-series (`ek-tm4c123gxl`) and everything seems to work fine. LGTM?

2024-10-18 23:01 UTC, Grazfather commented on archs/arm-openocd.py
> +        if "arm" in arch and arch.endswith("-m"):
there can be a variety of architectures

2024-10-18 23:03 UTC, Grazfather commented
@PowerUser64 thanks for testing this out. I just applied what should be a no-op change as suggested by @hugsy . Any chance you could try to ensure it still works? We can merge then. I just don't have the hardware accessible for a few days and I basically forgot this PR was still open, so it would be nice to merge.

2024-10-19 04:04 UTC, PowerUser64 commented
Seems to work! I'm able to place (hardware) breakpoints, go to next instructions, watch variables (done by halting pc every frame), and I get registers, stack, code, threads, and trace provided by gef. Would you like me to test loading arm-openocd.py in any way other than `source ./arm-openocd.py`, then `arch set armopenocd` after gef-extras is loaded? (Or is that the intended way?)

2024-10-19 16:13 UTC, Grazfather commented
Ah, you should use the `gef-openocd-remote` which also sets up the remote. How were you connecting to the target?

2024-10-20 09:51 UTC, PowerUser64 commented
I've been using this command to start openocd and connect to the board:
```bash
gef -ex 'target extended-remote | openocd -f board/ek-tm4c1294xl.cfg -c "gdb_port pipe; log_output openocd.log"; monitor reset; monitor halt' ./build/debug.axf
```

Using `gef-openocd-remote`, I get an error:
```bash
# *first, launched openocd from another terminal like this: openocd -f board/ti_ek-tm4c123gxl.cfg
# ...
gef> gef-openocd-remote localhost 3333
0x0000048e in SystemInit () at src/system_TM4C123.c:608608         for (i = 0; i < 10000; i++);   /* wait a while */
[*] Using `target remote` with GEF should work in most cases, but use `gef-remote` if you can. You can disable the overwrite of the `target remote` command by toggling `gef.disable_target_remote_overwrite` in the config.
[!] Command 'gef-openocd-remote' failed to execute properly, reason: Specified arch ARMOPENOCD is not supported 
```

In the error, it looks like it's capitalizing the architecture name. When I use `arch set`, I give it `armopenocd` in lowercase, but the error it's upper case.

However, I'm also noticing that I don't get the `gef-openocd-remote` command until after I do `source ./arm-openocd.py`, so it could be something with my environment. I feel like gef-extras should be loading this by default, along with the other "extra" things that it definitely _is_ loading, but it seems extra arches are unloaded by default. I checked the docs to see if it says how to load these, but I couldn't seem to find anything suggesting a way to automatically load it. Does gef provide a way to load files like arm-openocd.py other than putting `source /path/to/gef-extras/archs/arm-openocd.py` in `~/.gdbinit`?

2024-10-21 23:39 UTC, Grazfather commented
I manually source mine after gef.py and the rest of gef-extras. The arch selection should not be case sensitive. I can't repro this (without hardware atm) but will test with hardware this week.

If what you have is working, that's great! I've never seen the `gdb_port pipe` openocd command before.

2024-11-30 20:57 UTC, Grazfather commented
I finally had a use for this, and saw that lower case issue.

Pushed a fix in hugsy/gef#1159

2024-11-30 20:57 UTC, Grazfather commented
Should be ok to merge after that PR.

2024-12-09 07:32 UTC, hugsy approved these changes

2024-12-10 18:15 UTC, Grazfather commented
I can't merge for some reason

2025-01-03 17:29 UTC, hugsy approved these changes

2025-01-03 17:29 UTC, merged